import type { WorkflowDocument, WorkflowDocumentStep } from "@solow/contracts";
import { WORKFLOW_DOCUMENT_FORMAT, WORKFLOW_DOCUMENT_VERSION } from "@solow/contracts";
import { DEFAULT_WORKFLOW_ENTRIES } from "./defaults.js";
import { EVERYDAY_WORKFLOWS } from "./everyday.js";
import { OPENSPEC_WORKFLOWS } from "./openspec.js";
import type { VendoredStore } from "./sources.js";
import { SPECKIT_WORKFLOWS } from "./speckit.js";
import { SUPERPOWERS_WORKFLOWS } from "./superpowers.js";
import type { WorkflowStoreCategory, WorkflowStoreEntry, WorkflowStoreSkill } from "./types.js";
import vendoredJson from "./vendored.generated.json" with { type: "json" };

export * from "./sources.js";
export * from "./types.js";

/**
 * The Skills' text, as `scripts/sync-workflow-store.ts` fetched it from each owner's repository.
 * Generated, committed as the baseline a checkout builds from offline, and regenerated by CI
 * before every build — see `WORKFLOW_STORE_SOURCES`.
 */
export const VENDORED_STORE: VendoredStore = vendoredJson;

/** The catalog, in the order the store shows it: the seeds and the everyday pipelines first, the methods last. */
export const WORKFLOW_STORE: readonly WorkflowStoreEntry[] = [
  ...DEFAULT_WORKFLOW_ENTRIES,
  ...EVERYDAY_WORKFLOWS,
  ...SPECKIT_WORKFLOWS,
  ...SUPERPOWERS_WORKFLOWS,
  ...OPENSPEC_WORKFLOWS,
];

export const WORKFLOW_STORE_CATEGORIES: readonly { id: WorkflowStoreCategory; label: string }[] = [
  { id: "delivery", label: "Delivery" },
  { id: "review", label: "Review" },
  { id: "refactor", label: "Refactor" },
  { id: "bugfix", label: "Bug fix" },
  { id: "quality", label: "Quality" },
  { id: "maintenance", label: "Maintenance" },
  { id: "methodology", label: "Methods" },
];

/** The entries a fresh Workspace is seeded with, in seed order. */
export const WORKFLOW_STORE_SEEDS: readonly WorkflowStoreEntry[] = WORKFLOW_STORE.filter(
  (entry) => entry.seed === true,
);

export function workflowStoreEntry(id: string): WorkflowStoreEntry | undefined {
  return WORKFLOW_STORE.find((entry) => entry.id === id);
}

/**
 * The Skills an entry brings, with their vendored text, deduplicated by name — two Steps naming
 * one Skill, or two entries sharing one, is one row in the library. A name the generated file
 * does not hold is an error rather than a gap: `store:check` refuses that state before it is
 * built, so reaching it here means the catalog and the generated file are out of step.
 */
export function workflowStoreSkills(entry: WorkflowStoreEntry): WorkflowStoreSkill[] {
  const seen = new Set<string>();
  return entry.skills.flatMap((name) => {
    if (seen.has(name)) return [];
    seen.add(name);
    const vendored = VENDORED_STORE.skills[name];
    if (!vendored) throw new Error(`${entry.id}: skill ${name} is not vendored`);
    return [{ name, description: vendored.description, body: vendored.body }];
  });
}

/**
 * An entry as the document `workflow.import` reads, every Step on the named Harness Profile.
 *
 * The store has no opinion about harnesses — a pipeline is the same pipeline on any of them —
 * so the profile is the installer's choice, and it is written by *name* because that is what a
 * document carries and what the import resolves. Branch targets become indices here, which is
 * where a recipe naming a Step it does not have is caught: the document schema refuses an index
 * past the end, and this refuses a name with no index, so neither reaches the database.
 */
export function workflowStoreDocument(
  entry: WorkflowStoreEntry,
  harnessProfile: string,
): WorkflowDocument {
  const indexOf = new Map(entry.steps.map((step, index) => [step.name, index]));
  const target = (name: string | null): number | null => {
    if (name === null) return null;
    const index = indexOf.get(name);
    if (index === undefined) throw new Error(`${entry.id}: branch target "${name}" is not a step`);
    return index;
  };
  return {
    format: WORKFLOW_DOCUMENT_FORMAT,
    version: WORKFLOW_DOCUMENT_VERSION,
    name: entry.title,
    description: entry.description,
    steps: entry.steps.map(
      (step): WorkflowDocumentStep => ({
        name: step.name,
        harnessProfile,
        promptTemplate: step.prompt,
        gate: step.gate ?? "auto",
        advanceOn: step.advanceOn ?? "agent-signal",
        onEnter: null,
        branch: step.branch
          ? {
              when: step.branch.when,
              thenStep: target(step.branch.yes),
              elseStep: target(step.branch.no),
            }
          : null,
        mcpServers: [],
        skills: [...(step.skills ?? [])],
        permissionMode: step.permissionMode ?? null,
      }),
    ),
  };
}
